### ISSUE TITLE
Incorrect Points/Incoherences in the Database

### ISSUE THREAD

**Issue by GigiLoria5** [GigiLoria5/se2022-08-HireTracker#27]
Finally having the map available, it can be seen that the tracks and points specified are not consistent. For example, 'Trail to Monte Ziccher' presents 'Rifugio Blitz' in our DB as the starting point, however, as shown in the map, the blitz hut is located elsewhere and the actual starting point is another. 
![immagine](https://user-images.githubusercontent.com/41837640/203661134-afda83ab-67dc-4586-b4b1-64cad45a3981.png)

**Comment by antosams3** [comment]
The issue is that I take coordinates from google maps expecting as correct, but if I search the same locations on open street map the coordinates vary a little.. I'll manage to update on dev branch in the morning  
<img width="437" alt="image" src="https://user-images.githubusercontent.com/73968766/203726055-df9b1572-76e1-4bd1-9eda-4789d24dd42c.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/73968766/203726134-a9b1e80c-277f-4c22-980f-87e252ab2b6b.png">

**Comment by GigiLoria5** [comment]
The problem should have been solved thanks to the work of @FedeBel and @ciaccogiuseppe
