### ISSUE TITLE
Handling gpx data format

### ISSUE THREAD

**Issue by ciaccogiuseppe** [GigiLoria5/se2022-08-HireTracker#3]
I'm currently working on the api backend for storing gpx files sent by local guides. How should we handle storing the .gpx files? Shall we just save the gpx file and handle consintency and mapping within the backend logic?

**Comment by GigiLoria5** [comment]
Unfortunately, I don't have an absolute answer because I don't actually know how the gpx file library works. 
What I have imagined, however, is the following.

Saving phase:
1) the local guide when creating a new hike must also upload a 'name.gpx' file via the interface.
2) this file must be sent by the client to the server together with all the other data via API of course
3) the server validates all the data, validates the file a minimum, stores it in the relevant directory "server/gpx_files/" and then updates the database (saving only the file name in the relevant column).

In the request phase, the same thing must happen. The backend must expose an API in which it provides all the information of a hike, and if the request comes from an authenticated user it must send the .gpx file to the frontend (a task of the server, because the file resides in the subdirectory of the server). The file can be found by reading the name of the gpx file in the relevant column of the hike table.

**Comment by GigiLoria5** [comment]
Documenting online, I read that it is possible to send the file and data in a single request using the multipart/form-data content type.

**Comment by ciaccogiuseppe** [comment]
Didn't notice the gps_track column. Anyway I think frontend is actually thought to work with 2 APIs (one for the text data and one for the gpx file)
