### ISSUE TITLE
[GENERAL] Cover picture for huts and hikes

### ISSUE THREAD

**Issue by ciaccogiuseppe** [GigiLoria5/se2022-08-HireTracker#85]
Branch [feature_gciacco_be_pics](https://github.com/GigiLoria5/se2022-08-HikeTracker/tree/feature_gciacco_be_pics) contains all the changes needed for handling cover pictures for both huts and hikes in the backend.
Just a couple of notes for the frontend

- Automated E2E tests currently don't work, since FE APIs still need to be changed, so it's correct for the overall tests to fail
- When receiving the image in the frontend, a buffer will be received, so it's necessary to convert it (e.g. into a base64String) and using a compatible Image component (e.g. with a base64String, a <img src={\`data:image/png;base64,${imageB64Str}`}/>)
- All the existing hikes and hut now have a cover picture. Their aspect ratio is not constant (some of them are square, some other rectangular) as well as their resolution

**Comment by GigiLoria5** [comment]
Perfect, I'll update you if there are any problems. From my part, I can confirm that the image will appear only on the single page

**Comment by GigiLoria5** [comment]
@ciaccogiuseppe I almost finished everything, after some testing I found out that if the image is bigger than 1mb I cannot show the picture as base64String because the uri becomes too long and the browser does not show the whole picture. Instead of changing everything, I put 1MB as maximum size, I ask you to change the backend accordingly
